email_cfg:
  link_base: http://localhost:8000/verify-email?token=

db_cfg:
  base: postgresql+psycopg2
  user: postgres
  host: localhost
  password: admin
  port: 5432
  database: research_showcase

crypto_cfg:
  key: guys-this-is-secure-i-swear
  algorithm: HS256

token_cfg:
  access_token_expire_minutes: 60
  email_token_expire_minutes: 30

scheduler_cfg:
  delete_expired_users_interval_minutes: 60

tags_cfg:
  max_tags_per_post: 3
  tags_list:
    - Artificial Intelligence
    - Machine Learning
    - Deep Learning
    - Computer Vision
    - Natural Language Processing
    - Robotics
    - Internet of Things
    - Cybersecurity
    - Cloud Computing
    - Big Data
    - Data Mining
    - Wireless Networks
    - Signal Processing
    - Image Processing
    - Software Engineering
    - Computer Networks
    - Distributed Systems
    - Human-Computer Interaction
    - Embedded Systems
    - Quantum Computing
